server:
  port: 9090

spring:
  application:
    name: dextea-trade
  datasource:
    url: jdbc:mysql://localhost:8866/dextea?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: dextea
    password: REDACTED
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 3486
      password: REDACTED

cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: redis
  snowflake:
    enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.dextea.trade.entity
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
    path: /docs/json
  swagger-ui:
    enabled: true
    path: /docs/ui
    disable-swagger-default-url: true
  packages-to-scan: cn.dextea.trade.controller
  paths-to-match: /api/**
